# 应用配置
app:
  name: author-server
  version: 1.0.0
  env: dev
  jwt:
    secret: EScPnGep5uh-NdGtKwvfGn6Jrrnh9f-vK2THex7Jb4A
    expire-days: 7
    refresh-hours: 24
  thread-pool:
    core-pool-size: 4
    max-pool-size: 16
    queue-capacity: 500
    thread-name-prefix: login-worker-

# 服务器配置
server:
  port: 8001
  tomcat:
    threads:
      min-spare: 4
      max: 200
    connection-timeout: 30000
  compression:
    enabled: true
    mime-types: application/json

# Spring 配置
spring:
  application:
    name: author-server
  profiles:
    active: dev


# 日志配置
logging:
  config: classpath:logback.xml